# Generated by Django 5.0.7 on 2024-07-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(choices=[('KTL', 'KTL'), ('miltai', 'miltai'), ('KTL+miltai', 'KTL+miltai'), ('ZnPhos', 'ZnPhos'), ('Plovimas', 'Plovimas'), ('Papildomos paslaugos', 'Papildomos paslaugos'), ('Etiketavimas', 'Etiketavimas')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('adresas', models.CharField(blank=True, max_length=255, null=True)),
                ('telefonas', models.CharField(max_length=20)),
                ('email', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Detale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('brezinio_nr', models.CharField(max_length=255)),
                ('plotas', models.FloatField()),
                ('svoris', models.FloatField()),
                ('kiekis_metinis', models.IntegerField()),
                ('kiekis_menesis', models.IntegerField()),
                ('kiekis_partijai', models.IntegerField()),
                ('ppap_dokumentai', models.TextField()),
                ('standartas', models.CharField(blank=True, max_length=255, null=True)),
                ('kabinimo_tipas', models.CharField(blank=True, max_length=255, null=True)),
                ('kabinimas_xyz', models.CharField(blank=True, max_length=255, null=True)),
                ('kiekis_reme', models.IntegerField(blank=True, null=True)),
                ('faktinis_kiekis_reme', models.IntegerField(blank=True, null=True)),
                ('pakavimas', models.CharField(blank=True, max_length=255, null=True)),
                ('nuoroda_brezinio', models.CharField(blank=True, max_length=255, null=True)),
                ('nuoroda_pasiulymo', models.CharField(blank=True, max_length=255, null=True)),
                ('pastabos', models.TextField(blank=True, null=True)),
                ('danga', models.ManyToManyField(blank=True, to='detaliu_registras.danga')),
            ],
            options={
                'verbose_name': 'Detale',
                'verbose_name_plural': 'Detalės',
            },
        ),
        migrations.CreateModel(
            name='Kaina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busena', models.CharField(choices=[('aktuali', 'aktuali'), ('sena', 'sena')], max_length=20)),
                ('suma', models.FloatField()),
                ('yra_fiksuota', models.BooleanField(default=False)),
                ('kiekis_nuo', models.IntegerField(blank=True, null=True)),
                ('kiekis_iki', models.IntegerField(blank=True, null=True)),
                ('fiksuotas_kiekis', models.IntegerField(default=100, null=True)),
                ('detalė', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kainos', to='detaliu_registras.detale')),
            ],
            options={
                'verbose_name': 'Kaina',
                'verbose_name_plural': 'Kainos',
            },
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('uzklausos_data', models.DateField()),
                ('pasiulymo_data', models.DateField()),
                ('klientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.klientas')),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
        migrations.AddField(
            model_name='detale',
            name='projektas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.projektas'),
        ),
        migrations.CreateModel(
            name='Uzklausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.detale')),
                ('kaina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.kaina')),
                ('klientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.klientas')),
                ('projektas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.projektas')),
            ],
            options={
                'verbose_name': 'Užklausa',
                'verbose_name_plural': 'Užklausos',
            },
        ),
    ]
