# Generated by Django 5.0.7 on 2024-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0002_kaina_kainos_matas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detale',
            name='kiekis_menesis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
