# Generated by Django 5.0.7 on 2024-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0003_alter_detale_kiekis_menesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzklausa',
            name='kaina',
        ),
    ]
