# Generated by Django 5.2.5 on 2025-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0004_remove_uzklausa_kaina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klientas',
            old_name='email',
            new_name='el_pastas',
        ),
    ]
