# Generated by Django 5.2.5 on 2025-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0005_rename_email_klientas_el_pastas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detale',
            name='atlikimo_terminas_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='aukstis_x_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='ilgis_z_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabinimo_budas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabliukai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kontaktines_vietos_ktl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kontaktines_vietos_milt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kontaktiniu_vietu_pastaba',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='metalas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='metalo_storis_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='minimalus_kiekis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='nepilnas_remas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detale',
            name='padengimas_ktl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='padengimas_miltelinis_budas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='padengimo_standartas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='padengimo_storis_ktl_miltai_um',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='padengimo_storis_ktl_um',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakavimas_po_ktl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakavimas_po_miltelinio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakavimo_dienos_norma_vnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakavimo_instrukcija',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='partijos_dydis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='paruosimas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='plotis_y_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='spyruokle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='sukabinimas_pagal_fakta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detale',
            name='sukabinimo_dienos_norma_vnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='tara_kliento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='testai',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='tipas',
            field=models.CharField(choices=[('VIENETO', 'Kaina vnt.'), ('REMAS', 'Rėmo kaina'), ('PARTIJA', 'Kaina partijai'), ('KABLIUKAI', 'Kabliukų kaina'), ('PAK_MEDZ', 'Pakavimo medžiagų kaina'), ('DAZAI', 'Miltelinių dažų kaina'), ('DARBO', 'Darbo kaina'), ('SAVIKAINA', 'Viso savikaina'), ('FAKTINE', 'Faktinė kaina')], default='VIENETO', max_length=20),
        ),
        migrations.AddField(
            model_name='projektas',
            name='apmokejimo_salygos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='kaina_galioja_iki',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='projekto_pabaiga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='projekto_pradzia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='transportavimo_salygos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
