# Generated by Django 5.2.5 on 2025-09-16 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0006_detale_atlikimo_terminas_d_detale_aukstis_x_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detale',
            name='danga',
        ),
        migrations.AlterModelOptions(
            name='detale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kaina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='klientas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projektas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uzklausa',
            options={},
        ),
        migrations.RemoveField(
            model_name='detale',
            name='atlikimo_terminas_d',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='aukstis_x_cm',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='faktinis_kiekis_reme',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='ilgis_z_cm',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabinimas_xyz',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabinimo_budas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabinimo_tipas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabliukai',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_menesis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_metinis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_partijai',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_reme',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kontaktines_vietos_ktl',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kontaktines_vietos_milt',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kontaktiniu_vietu_pastaba',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='metalas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='metalo_storis_mm',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='minimalus_kiekis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nepilnas_remas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nuoroda_brezinio',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nuoroda_pasiulymo',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='padengimas_ktl',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='padengimas_miltelinis_budas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='padengimo_standartas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='padengimo_storis_ktl_miltai_um',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='padengimo_storis_ktl_um',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimas_po_ktl',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimas_po_miltelinio',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimo_dienos_norma_vnt',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimo_instrukcija',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='partijos_dydis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='paruosimas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pastabos',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='plotas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='plotis_y_cm',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='ppap_dokumentai',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='spyruokle',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='standartas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='sukabinimas_pagal_fakta',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='sukabinimo_dienos_norma_vnt',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='svoris',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='tara_kliento',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='testai',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='detalė',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='fiksuotas_kiekis',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='kainos_matas',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='kiekis_iki',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='kiekis_nuo',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='tipas',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='yra_fiksuota',
        ),
        migrations.RemoveField(
            model_name='klientas',
            name='adresas',
        ),
        migrations.RemoveField(
            model_name='klientas',
            name='telefonas',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='apmokejimo_salygos',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='kaina_galioja_iki',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='pasiulymo_data',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='projekto_pabaiga',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='projekto_pradzia',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='transportavimo_salygos',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='uzklausos_data',
        ),
        migrations.AddField(
            model_name='detale',
            name='kiekis',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kaina',
            name='uzklausa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kainos', to='detaliu_registras.uzklausa'),
        ),
        migrations.AddField(
            model_name='kaina',
            name='valiuta',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='projektas',
            name='aprasymas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uzklausa',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detale',
            name='brezinio_nr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detale',
            name='projektas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detales', to='detaliu_registras.projektas'),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='busena',
            field=models.CharField(choices=[('aktuali', 'Aktuali'), ('sena', 'Sena')], default='aktuali', max_length=10),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='el_pastas',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='vardas',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='klientas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projektai', to='detaliu_registras.klientas'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='detale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzklausos', to='detaliu_registras.detale'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='klientas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzklausos', to='detaliu_registras.klientas'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='projektas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzklausos', to='detaliu_registras.projektas'),
        ),
        migrations.CreateModel(
            name='DetalesIdentifikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pavadinimas', models.CharField(blank=True, max_length=128, null=True)),
                ('brezinio_numeris', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('paruosimas', models.TextField(blank=True, null=True)),
                ('detale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identifikacija', to='detaliu_registras.detale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalesSpecifikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('aukstis_x_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('plotis_y_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ilgis_z_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('metalo_storis_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('svoris_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('plotas_m2', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('metalas', models.CharField(blank=True, max_length=256, null=True)),
                ('detale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifikacija', to='detaliu_registras.detale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KabinimasRemai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kabinimo_budas', models.CharField(blank=True, choices=[('girliandos', 'Girliandos'), ('kablys', 'Kablys'), ('kita', 'Kita')], max_length=64, null=True)),
                ('kiekis_reme_planuotas', models.PositiveIntegerField(blank=True, null=True)),
                ('kiekis_reme_faktinis', models.PositiveIntegerField(blank=True, null=True)),
                ('kabliukai', models.CharField(blank=True, max_length=128, null=True)),
                ('spyruoke', models.CharField(blank=True, max_length=128, null=True)),
                ('kontaktines_vietos_ktl', models.TextField(blank=True, null=True)),
                ('kontaktines_vietos_miltelinis', models.TextField(blank=True, null=True)),
                ('nepilnas_remas', models.BooleanField(blank=True, null=True)),
                ('sukabinimo_dienos_norma_vnt', models.PositiveIntegerField(blank=True, null=True)),
                ('pakavimo_dienos_norma_vnt', models.PositiveIntegerField(blank=True, null=True)),
                ('uzklausa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kabinimas_remai', to='detaliu_registras.uzklausa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kainodara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kabliuku_kaina_vnt', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pakavimo_medziagu_kaina_vnt', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('milteliniu_dazu_kaina_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('darbo_kaina', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('viso_savikaina', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiksuota_kaina_vnt', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remo_kaina', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('faktine_kaina', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sukabinimas_pagal_fakta', models.PositiveIntegerField(blank=True, null=True)),
                ('valiuta', models.CharField(blank=True, default='EUR', max_length=8, null=True)),
                ('uzklausa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kainodara', to='detaliu_registras.uzklausa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KainosPartijai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('partijos_kiekis_vnt', models.PositiveIntegerField(db_index=True)),
                ('kaina_bendra', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('kainodara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kainos_partijoms', to='detaliu_registras.kainodara')),
            ],
        ),
        migrations.CreateModel(
            name='KiekiaiTerminai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('metinis_kiekis_vnt', models.PositiveIntegerField(blank=True, null=True)),
                ('partijos_dydis_vnt', models.PositiveIntegerField(blank=True, null=True)),
                ('minimalus_kiekis_vnt', models.PositiveIntegerField(blank=True, null=True)),
                ('terminai_darbo_dienomis', models.PositiveIntegerField(blank=True, null=True)),
                ('uzklausa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kiekiai_terminai', to='detaliu_registras.uzklausa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pakavimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tara', models.CharField(blank=True, max_length=128, null=True)),
                ('pakavimo_instrukcija', models.TextField(blank=True, null=True)),
                ('pakavimas_po_ktl', models.TextField(blank=True, null=True)),
                ('pakavimas_po_miltelinio', models.TextField(blank=True, null=True)),
                ('papildomos_paslaugos', models.TextField(blank=True, null=True)),
                ('uzklausa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pakavimas', to='detaliu_registras.uzklausa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pastaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kategorija', models.CharField(blank=True, choices=[('projektas', 'Projektas'), ('identifikacija', 'Identifikacija'), ('paviršiai', 'Paviršiai'), ('matmenys', 'Matmenys/medžiaga'), ('kiekiai', 'Kiekiai/terminai'), ('kabinimas', 'Kabinimas/rėmai'), ('pakavimas', 'Pakavimas'), ('kainodara', 'Kainodara'), ('kita', 'Kita')], db_index=True, max_length=32, null=True)),
                ('tekstas', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastabos_autoriai', to=settings.AUTH_USER_MODEL)),
                ('uzklausa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastabos', to='detaliu_registras.uzklausa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PavirsiaiDangos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ktl_ec_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Padengimas KTL / e-coating')),
                ('miltelinis_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Padengimas milteliniu būdu')),
                ('storis_ktl_mkm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Padengimas, storis μm KTL')),
                ('storis_ktl_plus_miltai_mkm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Padengimo storis: KTL + miltai, μm')),
                ('padengimo_standartas', models.CharField(blank=True, max_length=128, null=True)),
                ('testai', models.TextField(blank=True, null=True)),
                ('detale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pavirsiu_dangos', to='detaliu_registras.detale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UzklausosProjektoDuomenys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uzklausos_nr', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('uzklausos_data', models.DateField(blank=True, null=True)),
                ('pasiulymo_data', models.DateField(blank=True, null=True)),
                ('projekto_pradzia_metai', models.PositiveIntegerField(blank=True, null=True)),
                ('projekto_pabaiga_metai', models.PositiveIntegerField(blank=True, null=True)),
                ('kaina_vnt', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('kaina_galioja_iki', models.DateField(blank=True, null=True)),
                ('apmokejimo_salygos', models.CharField(blank=True, max_length=128, null=True)),
                ('transportavimo_salygos', models.CharField(blank=True, max_length=64, null=True)),
                ('atsakingas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzklausos_atsakingas', to=settings.AUTH_USER_MODEL)),
                ('uzklausa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projekto_duomenys', to='detaliu_registras.uzklausa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Danga',
        ),
        migrations.AddIndex(
            model_name='kainospartijai',
            index=models.Index(fields=['partijos_kiekis_vnt'], name='detaliu_reg_partijo_3e332e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kainospartijai',
            unique_together={('kainodara', 'partijos_kiekis_vnt')},
        ),
    ]
