# Generated by Django 5.2.5 on 2025-09-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0007_remove_detale_danga_alter_detale_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaleSpecifikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('metalas', models.CharField(blank=True, max_length=255, null=True)),
                ('plotas_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('svoris_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('medziagos_kodas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PavirsiuDangos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('ktl_ec_name', models.CharField(blank=True, max_length=255, null=True)),
                ('miltelinis_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spalva_ral', models.CharField(blank=True, max_length=64, null=True)),
                ('blizgumas', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='detalesidentifikacija',
            name='detale',
        ),
        migrations.RemoveField(
            model_name='detalesspecifikacija',
            name='detale',
        ),
        migrations.RemoveField(
            model_name='kabinimasremai',
            name='uzklausa',
        ),
        migrations.RemoveField(
            model_name='kiekiaiterminai',
            name='uzklausa',
        ),
        migrations.RemoveField(
            model_name='pakavimas',
            name='uzklausa',
        ),
        migrations.RemoveField(
            model_name='pastaba',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pastaba',
            name='uzklausa',
        ),
        migrations.RemoveField(
            model_name='pavirsiaidangos',
            name='detale',
        ),
        migrations.RemoveField(
            model_name='uzklausosprojektoduomenys',
            name='atsakingas',
        ),
        migrations.RemoveField(
            model_name='uzklausosprojektoduomenys',
            name='uzklausa',
        ),
        migrations.AlterModelOptions(
            name='kaina',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='kainospartijai',
            name='detaliu_reg_partijo_3e332e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='kainospartijai',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='projektas',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='darbo_kaina',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='faktine_kaina',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='fiksuota_kaina_vnt',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='kabliuku_kaina_vnt',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='milteliniu_dazu_kaina_kg',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='pakavimo_medziagu_kaina_vnt',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='remo_kaina',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='sukabinimas_pagal_fakta',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='valiuta',
        ),
        migrations.RemoveField(
            model_name='kainodara',
            name='viso_savikaina',
        ),
        migrations.RemoveField(
            model_name='klientas',
            name='el_pastas',
        ),
        migrations.AddField(
            model_name='detale',
            name='aukstis_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='ilgis_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabinimo_anga_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabinimo_budas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabinti_per',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kabliuku_kiekis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kiekis_menesis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kiekis_metinis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kiekis_partijai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='kiekis_per_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakuotes_pastabos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='pakuotes_tipas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='plotis_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='ppap_dokumentai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='priedai_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='skersmuo_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='storis_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='testai_druskos_rukas_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='testai_kita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='testas_adhezija',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='testas_storis_mikronai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='vienetai_dezeje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='vienetai_paleje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='fiksuotas_kiekis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='kainos_matas',
            field=models.CharField(blank=True, choices=[('vnt', 'Vnt'), ('m2', 'm²'), ('kg', 'kg'), ('val', 'val.')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='kiekis_iki',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='kiekis_nuo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='yra_fiksuota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kainodara',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kainodara',
            name='pavadinimas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kainodara',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='kiekis_iki',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='kiekis_nuo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='suma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kainospartijai',
            name='valiuta',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='klientas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='klientas',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='uzklausa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uzklausa',
            name='pastabos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uzklausa',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='uzklausa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='kainos', to='detaliu_registras.uzklausa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kainodara',
            name='uzklausa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kainodaros', to='detaliu_registras.uzklausa'),
        ),
        migrations.AlterField(
            model_name='kainospartijai',
            name='kainodara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partijos', to='detaliu_registras.kainodara'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='detale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzklausos', to='detaliu_registras.detale'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='klientas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzklausos', to='detaliu_registras.klientas'),
        ),
        migrations.AlterField(
            model_name='uzklausa',
            name='projektas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzklausos', to='detaliu_registras.projektas'),
        ),
        migrations.AddField(
            model_name='detalespecifikacija',
            name='detale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifikacija', to='detaliu_registras.detale'),
        ),
        migrations.AddField(
            model_name='pavirsiudangos',
            name='detale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pavirsiu_dangos', to='detaliu_registras.detale'),
        ),
        migrations.DeleteModel(
            name='DetalesIdentifikacija',
        ),
        migrations.DeleteModel(
            name='DetalesSpecifikacija',
        ),
        migrations.DeleteModel(
            name='KabinimasRemai',
        ),
        migrations.DeleteModel(
            name='KiekiaiTerminai',
        ),
        migrations.DeleteModel(
            name='Pakavimas',
        ),
        migrations.DeleteModel(
            name='Pastaba',
        ),
        migrations.DeleteModel(
            name='PavirsiaiDangos',
        ),
        migrations.DeleteModel(
            name='UzklausosProjektoDuomenys',
        ),
        migrations.RemoveField(
            model_name='kainospartijai',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kainospartijai',
            name='kaina_bendra',
        ),
        migrations.RemoveField(
            model_name='kainospartijai',
            name='partijos_kiekis_vnt',
        ),
        migrations.RemoveField(
            model_name='kainospartijai',
            name='updated_at',
        ),
    ]
