# Generated by Django 5.2.5 on 2025-09-25 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0008_detalespecifikacija_pavirsiudangos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaina',
            options={'ordering': ['-galioja_nuo', '-id']},
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='busena',
        ),
        migrations.AddField(
            model_name='detale',
            name='nuoroda_brezinio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='nuoroda_pasiulymo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='projektas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detales', to='detaliu_registras.projektas'),
        ),
        migrations.AddField(
            model_name='kaina',
            name='detale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kainos', to='detaliu_registras.detale'),
        ),
        migrations.AddField(
            model_name='kaina',
            name='galioja_iki',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='galioja_nuo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kaina',
            name='keitimo_priezastis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='pakeite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kainu_keitimai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kaina',
            name='yra_aktuali',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='apmokejimo_salygos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='kaina_galioja_iki',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='pasiulymo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='projekto_pabaiga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='projekto_pradzia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='transportavimo_salygos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projektas',
            name='uzklausos_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='kaina',
            index=models.Index(fields=['uzklausa', 'yra_aktuali'], name='detaliu_reg_uzklaus_78ce5c_idx'),
        ),
        migrations.AddIndex(
            model_name='kaina',
            index=models.Index(fields=['uzklausa', 'galioja_nuo'], name='detaliu_reg_uzklaus_42921b_idx'),
        ),
        migrations.AddConstraint(
            model_name='kaina',
            constraint=models.UniqueConstraint(condition=models.Q(('yra_aktuali', True)), fields=('uzklausa', 'detale'), name='unikali_aktuali_kaina_per_uzklausa_detale'),
        ),
    ]
