# Generated by Django 5.2.5 on 2025-10-04 19:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0009_alter_kaina_options_remove_kaina_busena_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDetale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pavadinimas', models.CharField(max_length=255)),
                ('brezinio_nr', models.CharField(blank=True, max_length=255, null=True)),
                ('nuoroda_brezinio', models.CharField(blank=True, max_length=500, null=True)),
                ('nuoroda_pasiulymo', models.CharField(blank=True, max_length=500, null=True)),
                ('kiekis_metinis', models.IntegerField(blank=True, null=True)),
                ('kiekis_menesis', models.IntegerField(blank=True, null=True)),
                ('kiekis_partijai', models.IntegerField(blank=True, null=True)),
                ('kiekis_per_val', models.IntegerField(blank=True, null=True)),
                ('ilgis_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plotis_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('aukstis_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skersmuo_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('storis_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kabinimo_budas', models.CharField(blank=True, max_length=255, null=True)),
                ('kabliuku_kiekis', models.IntegerField(blank=True, null=True)),
                ('kabinimo_anga_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kabinti_per', models.CharField(blank=True, max_length=255, null=True)),
                ('pakuotes_tipas', models.CharField(blank=True, max_length=255, null=True)),
                ('vienetai_dezeje', models.IntegerField(blank=True, null=True)),
                ('vienetai_paleje', models.IntegerField(blank=True, null=True)),
                ('pakuotes_pastabos', models.CharField(blank=True, max_length=255, null=True)),
                ('testai_druskos_rukas_val', models.IntegerField(blank=True, null=True)),
                ('testas_adhezija', models.CharField(blank=True, max_length=255, null=True)),
                ('testas_storis_mikronai', models.IntegerField(blank=True, null=True)),
                ('testai_kita', models.CharField(blank=True, max_length=255, null=True)),
                ('ppap_dokumentai', models.CharField(blank=True, max_length=255, null=True)),
                ('priedai_info', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projektas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='detaliu_registras.projektas')),
            ],
            options={
                'verbose_name': 'historical detale',
                'verbose_name_plural': 'historical detales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
