# Generated by Django 5.2.5 on 2025-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0010_historicaldetale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldetale',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetale',
            name='projektas',
        ),
        migrations.AlterModelOptions(
            name='kaina',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='kaina',
            name='unikali_aktuali_kaina_per_uzklausa_detale',
        ),
        migrations.RemoveIndex(
            model_name='kaina',
            name='detaliu_reg_uzklaus_78ce5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='kaina',
            name='detaliu_reg_uzklaus_42921b_idx',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nuoroda_brezinio',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nuoroda_pasiulymo',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='projektas',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='detale',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='galioja_iki',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='galioja_nuo',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='keitimo_priezastis',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='pakeite',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='yra_aktuali',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='apmokejimo_salygos',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='kaina_galioja_iki',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='pasiulymo_data',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='projekto_pabaiga',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='projekto_pradzia',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='transportavimo_salygos',
        ),
        migrations.RemoveField(
            model_name='projektas',
            name='uzklausos_data',
        ),
        migrations.AddField(
            model_name='kaina',
            name='busena',
            field=models.CharField(choices=[('aktuali', 'Aktuali'), ('sena', 'Sena')], default='aktuali', max_length=10),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='HistoricalDetale',
        ),
    ]
