"""
Visų pozicijų sąrašo stulpelių schema.

- key:    modelio laukas arba property
- label:  stulpelio pavadinimas
- type:   "char" | "number" | "date" | "virtual"
- filter: "text" | "range" | "date" | None
- searchable: ar dalyvauja globalioje q paieškoje
- width:  numanomam stulpelio pločiui (px)
- default: ar rodomas pagal nutylėjimą
"""

COLUMNS: list[dict] = [
    # ---------------- Pagrindinė info ----------------
    {
        "key": "klientas",
        "label": "Klientas",
        "type": "char",
        "filter": "text",
        "searchable": True,
        "width": 180,
        "default": True,
    },
    {
        "key": "projektas",
        "label": "Projektas",
        "type": "char",
        "filter": "text",
        "searchable": True,
        "width": 160,
        "default": True,
    },
    {
        "key": "poz_kodas",
        "label": "Pozicijos kodas",
        "type": "char",
        "filter": "text",
        "searchable": True,
        "width": 150,
        "default": True,
    },
    {
        "key": "poz_pavad",
        "label": "Pozicijos pavadinimas",
        "type": "char",
        "filter": "text",
        "searchable": True,
        "width": 260,
        "default": True,
    },

    # ---------------- Specifikacija ----------------
    {
        "key": "metalas",
        "label": "Metalas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 120,
        "default": True,
    },
    {
        "key": "metalo_storiai_display",
        "label": "Metalo storis",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 120,
        "default": True,
    },
    {
        "key": "plotas",
        "label": "Plotas",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 90,
        "default": False,
        "align": "right",
    },
    {
        "key": "svoris",
        "label": "Svoris",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 90,
        "default": False,
        "align": "right",
    },
    {
        "key": "matmenys_xyz",
        "label": "Matmenys (xyz)",
        "type": "virtual",
        "filter": None,
        "searchable": False,
        "width": 140,
        "default": True,
    },

    # ---------------- Kabinimas (nauja struktūra) ----------------
    {
        "key": "ktl_kabinimo_budas",
        "label": "KTL kabinimo būdas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 150,
        "default": False,
    },
    {
        "key": "ktl_kabinimas_reme_txt",
        "label": "KTL kabinimas rėme",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 150,
        "default": False,
    },
    {
        "key": "ktl_detaliu_kiekis_reme",
        "label": "KTL detalių kiekis rėme",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 140,
        "default": False,
        "align": "right",
    },
    {
        "key": "ktl_faktinis_kiekis_reme",
        "label": "KTL faktinis kiekis rėme",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 150,
        "default": False,
        "align": "right",
    },
    {
        "key": "miltai_kiekis_per_valanda",
        "label": "Miltai kiekis/val.",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 130,
        "default": False,
        "align": "right",
    },
    {
        "key": "miltai_detaliu_kiekis_reme",
        "label": "Miltai detalių kiekis rėme",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 170,
        "default": False,
        "align": "right",
    },
    {
        "key": "miltai_faktinis_kiekis_reme",
        "label": "Miltai faktinis kiekis rėme",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 170,
        "default": False,
        "align": "right",
    },

    # ---------------- Paslauga (paviršius / dažymas) ----------------
    {
        "key": "paruosimas",
        "label": "Paruošimas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 140,
        "default": False,
    },
    {
        "key": "padengimas",
        "label": "Padengimas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 140,
        "default": True,
    },
    {
        "key": "padengimo_standartas",
        "label": "Padengimo standartas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 160,
        "default": False,
    },
    {
        "key": "ktl_dangos_storis_display",
        "label": "KTL storis, µm",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 120,
        "default": True,
    },
    {
        "key": "miltai_dangos_storis_display",
        "label": "Miltai storis, µm",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 130,
        "default": True,
    },
    {
        "key": "partiju_dydziai",
        "label": "Partijų dydžiai",
        "type": "char",
        "filter": "text",
        "searchable": True,
        "width": 140,
        "default": True,
    },
    {
        "key": "metiniai_kiekiai_display",
        "label": "Metiniai kiekiai",
        "type": "virtual",
        "filter": "text",
        "searchable": False,
        "width": 130,
        "default": True,
    },
    {
        "key": "projekto_gyvavimo_display",
        "label": "Projekto laikotarpis",
        "type": "virtual",
        "filter": "text",
        "searchable": False,
        "width": 160,
        "default": True,
    },
    {
        "key": "spalva",
        "label": "Spalva",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 120,
        "default": False,
    },

    # ---------------- Maskavimas ----------------
    {
        "key": "maskavimo_tipas",
        "label": "Maskavimas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 140,
        "default": False,
    },

    # ---------------- Kiti techniniai ----------------
    {
        "key": "testai_kokybe",
        "label": "Testai / kokybė",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 180,
        "default": False,
    },
    {
        "key": "atlikimo_terminas",
        "label": "Atlikimo terminas (d.d.)",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 140,
        "default": False,
        "align": "right",
    },

    # ---------------- Pakavimas ----------------
    {
        "key": "pakavimo_tipas",
        "label": "Pakavimas",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 140,
        "default": False,
    },

    # ---------------- Kaina / pastabos ----------------
    {
        "key": "kaina_eur",
        "label": "Kaina, EUR",
        "type": "number",
        "filter": "range",
        "searchable": False,
        "width": 100,
        "default": True,
        "align": "right",
    },
    {
        "key": "pastabos",
        "label": "Pastabos",
        "type": "char",
        "filter": "text",
        "searchable": False,
        "width": 260,
        "default": False,
    },

    # ---------------- Sisteminiai ----------------
    {
        "key": "created",
        "label": "Sukurta",
        "type": "date",
        "filter": "date",
        "searchable": False,
        "width": 120,
        "default": False,
    },
    {
        "key": "updated",
        "label": "Atnaujinta",
        "type": "date",
        "filter": "date",
        "searchable": False,
        "width": 120,
        "default": False,
    },

    # ---------------- Virtualūs laukai ----------------
    {
        "key": "brez_count",
        "label": "Brėžiniai",
        "type": "virtual",
        "filter": None,
        "searchable": False,
        "width": 90,
        "default": False,
    },
    {
        "key": "dok_count",
        "label": "Dokumentai",
        "type": "virtual",
        "filter": None,
        "searchable": False,
        "width": 100,
        "default": False,
    },
]
