# Generated by Django 5.2.5 on 2026-02-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pozicijos', '0002_pozicija_pagrindiniai_kodai'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpozicija',
            name='brezinio_nr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Brėžinio Nr.'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ieinantis_kodas',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Įeinantis kodas'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='iseinantis_kodas',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Išeinantis kodas'),
        ),
    ]
