# Generated by Django 5.2.5 on 2026-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0003_historicalpozicija_brezinio_nr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pozicijosbrezinys',
            options={'ordering': ['eiliskumas', 'id'], 'verbose_name': 'Pozicijos brėžinys', 'verbose_name_plural': 'Pozicijų brėžiniai'},
        ),
        migrations.AddField(
            model_name='pozicijosbrezinys',
            name='eiliskumas',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Eiliškumas'),
        ),
    ]
